### ISSUE TITLE
[Minecraft v1.20.4] - Health Indications v2.3

### ISSUE THREAD

**Issue by BakaTekku** [DansDatapacks/Health-Indications#1]
Not working on this version the health indication is borked.
`[16:31:49] [Worker-Main-4/ERROR]: Couldn't load tag sourcecraft.5:passable as it is missing following references: minecraft:grass (from file/Health Indications v2.3 [1.20+] (Resourcepack Options Enabled).zip)`
![2024-03-27_16 35 57](https://github.com/DansDatapacks/Health-Indications/assets/28825262/c51a9b59-6d7a-47ea-a888-6c74c66c50da)

**Comment by Dan-Mizu** [comment]
The error is irrelevant to the issue. I believe that the resourcepack is outdated.

**Comment by BakaTekku** [comment]
I had a feeling that might be it.
Any chance for a fix?

**Comment by Dan-Mizu** [comment]
Yea I'll try to get around to it, but I have to look into the changes to see what needs to be fixed.

**Comment by Dan-Mizu** [comment]
> Not working on this version the health indication is borked. `[16:31:49] [Worker-Main-4/ERROR]: Couldn't load tag sourcecraft.5:passable as it is missing following references: minecraft:grass (from file/Health Indications v2.3 [1.20+] (Resourcepack Options Enabled).zip)` ![2024-03-27_16 35 57](https://private-user-images.githubusercontent.com/28825262/317524280-c51a9b59-6d7a-47ea-a888-6c74c66c50da.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE2Njg0MDQsIm5iZiI6MTcxMTY2ODEwNCwicGF0aCI6Ii8yODgyNTI2Mi8zMTc1MjQyODAtYzUxYTliNTktNmQ3YS00N2VhLWE4ODgtNmM3NGM2NmM1MGRhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI4VDIzMjE0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM3YjNkMGUwMDcyNzg3MjA4NDhhODZmNTUyY2RmNzBiMWQxZTljNzcxODBlZjcyNmEyMWY1MWZhZjBkNGQxZTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.OZXk_k7m7x2UDSHBmUqaBgo6Tx-dTurJdmki62ibyi4)

Are you sure that you put the same file in both your datapack and resourcepack folders, and enabled the resourcepack in your settings? I believe the healthbar textures should still be working.
