### ISSUE TITLE
Would it be possible to set a delay for showing health bars when a player joins the game?

### ISSUE THREAD

**Issue by FaultyFunctions** [DansDatapacks/Health-Indications#2]
Hello! I am currently using ItemsAdder to load the server resource pack including the assets from the custom resource pack. So resources aren't loaded immediately like they are with a local resource pack. If there is a health bar on an entity when you join the game, the health bar will show a bunch of square unicode symbols and will continue to do so even after the resource pack is loaded (until the bar goes away or is updated again).

Would it be possible to set a delay on loading health bars after a player joins the game? Or maybe force updating the health bars after a certain amount of time passes? Is it possible to detect when a server resource pack is loaded? I'm not sure what the best course of action here would be. Lemme know, thanks!

**Comment by FaultyFunctions** [comment]
A workaround for the time being is to just not use the custom resource pack if anyone else experiences this.

**Comment by Dan-Mizu** [comment]
>  So resources aren't loaded immediately like they are with a local resource pack. If there is a health bar on an entity when you join the game, the health bar will show a bunch of square unicode symbols and will continue to do so even after the resource pack is loaded (until the bar goes away or is updated again).

This issue shouldn't be unique to my pack so your solution should be found from whatever services or software you use to load the packs. I would recommend asking those in the ItemsAdder community for a solution.
