### ISSUE TITLE
MythicMobs plugin issue

### ISSUE THREAD

**Issue by Schnell1337** [DansDatapacks/Health-Indications#3]
I use a datapack on my server with plugin MythicMobs that adds custom mobs. I’m having an issue with one of my mobs - the health bar is glitchy, and I would like to remove the health bar entirely. Do you have any command in the function that can exclude specific mobs?

**Comment by Dan-Mizu** [comment]
Yes. I believe the `global.ignore` is a common tag that you can add to an entity that datapacks use to ignore them, which this one employs. You can also use `healthindications.ignore` if you want it to be more specific.
